spring:
  datasource:
    username: spi
    password: spi
    url: jdbc:mysql://localhost:3306/dbtest?createDatabaseIfNotExist=true&useSSL=false?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring.sql.init.data-locations: file:schema.sql

server:
  port: 8081